name: Cloud Resume Challenge
on:
  push
env:
  BUCKET_NAME : "s3://ctvw.xyz"
  AWS_REGION : "us-east-1"
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  CloudFormation:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Sam Setup
        uses: aws-actions/setup-sam@v2
        with: 
          use installer: true
          aws-region: ${{ env.AWS_REGION }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::530285208563:role/github-oidc-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: cloudresumechallenge
      - run: sam build -t cloudresume/template.yaml --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::530285208563:role/github-oidc-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: cloudresumechallenge
      # Upload a file to AWS s3
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./website/ ${{ env.BUCKET_NAME }}/
      #Invalidate CloudFront Cache
      - name: invalidate cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION }} --paths "/*"